# docker-compose file

version: '3.3'

services:
  lms:
    build: .
    image: noghost:lms
    expose:
      - 80
      - 27960
    command: sh -c "service apache2 start && node build/ioq3ded.js +set net_port 27960 +set fs_game NoGhost +set fs_cdn 'locustv2.com:8080' +set dedicated 2 +exec last-man-railing.cfg"

  ctf:
    build: .
    image: noghost:ctf
    expose:
      - 27961
    command: sh -c "service apache2 start && node build/ioq3ded.js +set net_port 27961 +set fs_game NoGhost +set fs_cdn 'locustv2.com:8080' +set dedicated 2 +exec capture-the-flag-demo.cfg"

  freeze:
    build: .
    image: noghost:freeze
    expose:
      - 27962
    command: sh -c "service apache2 start && node build/ioq3ded.js +set net_port 27962 +set fs_game NoGhost +set fs_cdn 'locustv2.com:8080' +set dedicated 2 +exec freeze-death-match.cfg"

  ctf2:
    build: .
    image: noghost:ctf2
    expose:
      - 27961
    command: sh -c "service apache2 start && node build/ioq3ded.js +set net_port 27963 +set fs_game NoGhost +set fs_cdn 'locustv2.com:8080' +set dedicated 2 +exec capture-the-flag-demo.cfg"

  nginx:
    restart: always
    domainname: local.games
    image: nginx:latest
    ports:
      - "8080:80"
      - "27960:27960"
      - "27961:27961"
      - "27962:27962"
      - "27963:27963"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

