# docker-compose file

version: '3.3'

services:
  lms:
    build:
      context: .
      args:
        ARG HOSTNAME: locustv2.com
        ARG WEB_PORT: 8080
        ARG GAME_PORT: 27960
        ARG DEDICATED: 2
        ARG CONFIG: lms.cfg
    image: noghost:lms
    ports:
      - 8080:80
      - 27960:27960
