# docker-compose file

version: '3.3'

services:
  lms:
    build: .
    image: noghost:lms
    expose:
      - 80
      - 27960
    command: sh -c "service apache2 start && node build/ioq3ded.js +set net_port 27960 +set fs_game NoGhostX +set fs_cdn 'locustv2.com:8080' +set dedicated 2 +exec last-man-railing.cfg"
    volumes:
      - ./customcfg:/home/quake/quakejs/base/NoGhostX

  ctf:
    build: .
    image: noghost:ctf
    expose:
      - 27961
    command: sh -c "service apache2 start && node build/ioq3ded.js +set net_port 27961 +set fs_game NoGhostX +set fs_cdn 'locustv2.com:8080' +set dedicated 2 +exec capture-the-flag-demo.cfg"
    volumes:
      - ./customcfg:/home/quake/quakejs/base/NoGhostX

  freeze:
    build: .
    image: noghost:freeze
    expose:
      - 27962
    command: sh -c "service apache2 start && node build/ioq3ded.js +set net_port 27962 +set fs_game NoGhostX +set fs_cdn 'locustv2.com:8080' +set dedicated 2 +exec freeze-death-match.cfg"
    volumes:
      - ./customcfg:/home/quake/quakejs/base/NoGhostX

  ctf2:
    build: .
    image: noghost:ctf2
    expose:
      - 27961
    command: sh -c "service apache2 start && node build/ioq3ded.js +set net_port 27963 +set fs_game NoGhostX +set fs_cdn 'locustv2.com:8080' +set dedicated 2 +exec capture-the-flag-x.cfg"
    volumes:
      - ./customcfg:/home/quake/quakejs/base/NoGhostX

  nginx:
    restart: always
    domainname: local.games
    image: nginx:latest
    ports:
      - "8080:80"
      - "27960:27960"
      - "27961:27961"
      - "27962:27962"
      - "27963:27963"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  test:
    build: .
    image: noghost:test
    ports:
      - 27960:27960
      - 80:80
    command: sh -c "service apache2 start && node build/ioq3ded.js +set net_port 27960 +set fs_game NoGhostX +set fs_cdn '127.0.0.1:80' +set dedicated 2 +exec capture-the-flag-x.cfg"
    volumes:
      - ./customcfg:/home/quake/quakejs/base/NoGhostX


  db:
    # image: mysql:8.0.23
    image: mariadb:10.5.9
    restart: always
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: vsp
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
  stats:
    image: evilru/quake3-vsp-stats:latest
    restart: always
    depends_on:
      - db
    volumes:
      # - /path/to/your/games.log:/vsp/games.log
      # - /path/to/your/server.gif:/vsp/pub/images/server.gif
      # - /path/to/your/logo.gif:/vsp/pub/images/logo.gif
      - ./customcfg/lms.log:/vsp/games.log
    ports:
      - 27970:80
      # supervisor web gui would be available on port 9001
      - 9001:9001
    environment:
      TZ: Europe/Berlin
      # VSP_WEB_PASSWORD: vspweb
      DB_HOSTNAME: db
      DB_NAME: vsp
      DB_USERNAME: devuser
      DB_PASSWORD: devpass
      LOGTYPE: q3a
      SERVER_TITLE: Last Man Railing
      SERVER_NAME_IP: 34.91.145.88:27960
      SERVER_GAME_MOD: NoGhostX
      SERVER_ADMINS: ^1zed
      WEB_SITE_ADDRESS: http://www.quakejs.com/play?connect%2034.91.145.88:27960
      WEB_SITE_NAME: quakejs
      DEFAULT_SKIN: xp
      SERVER_QUOTE: Kill or be finished!
      SERVER_EMAIL_IM: N/A
