# docker-compose file

version: '3.3'

services:
  lms:
    build:
      context: .
      args:
        HOSTNAME: locustv2.com
        WEB_PORT: 8080
        GAME_PORT: 27960
        DEDICATED: 2
        CONFIG: lms.cfg
    image: noghost:lms
    ports:
      - 8080:80
      - 27960:27960
